### ISSUE TITLE
Duplicate declaration errors after upgrade from v1.0.2 to v1.1.0

### ISSUE THREAD

**Issue by SDpyro** [pdxcat/puppet-module-autofs#21]
If I downgrade I no longer get the errors.

Excerpt from my configs (note: I tried with and without the mapfile lines here):

  autofs::mount { '/home.net':
    map     => '/etc/auto.home',
    options => '--ghost',
    mapfile => '/etc/auto.master',
  }
  autofs::mount { '/misc':
    map     => '/etc/auto.misc',
    options => '--ghost',
    mapfile => '/etc/auto.master',
  }
  autofs::mount { '/net':
    map     => '-hosts',
    mapfile => '/etc/auto.master',
  }
  autofs::mount { '/-':
    map     => '/etc/auto.local',
    mapfile => '/etc/auto.master',
  }

**Comment by jkroepke** [comment]
Looks like it is fixed on master branch.

**Comment by SDpyro** [comment]
It sure "says" it is fixed. But after a fresh install. It still produces the error.

**Comment by SDpyro** [comment]
OK, I found the problem here.
If you have puppetlabs-concat >= 2.0.0  you will have this error.
You will need to downgrade to v1.2.4. If you look here
https://forge.puppetlabs.com/puppetlabs/concat
you will see that 2.0.0 and 2.0.1 are deleted due to bugs.

**Comment by tuxbiker** [comment]
Can confirm. This still exists. This module appears to have been abandoned?

**Comment by jkroepke** [comment]
Hi! looks like its not longer supported.

I have create an fork https://forge.puppet.com/jkroepke/autofs, but its not 100% backward compatible
